import { NgModule } from '@angular/core';

@NgModule({
  imports: [
    // MatButtonModule,
    // MatFormFieldModule,
    // MatInputModule,
    // MatDialogModule,
    // MatSelectModule,
    // MatSnackBarModule,
    // MatDatepickerModule,
    // MatCheckboxModule,
    // MatIconModule,
    // MatSlideToggleModule,
    // MatRadioModule,
    // MatSliderModule,
    // MatNativeDateModule,
    // MatMenuModule,
    // MatPaginatorModule,
    // MatProgressSpinnerModule,
    // MatTabsModule,
  ],
  exports: [
    // MatButtonModule,
    // MatFormFieldModule,
    // MatInputModule,
    // MatDialogModule,
    // MatSelectModule,
    // MatSnackBarModule,
    // MatDatepickerModule,
    // MatCheckboxModule,
    // MatIconModule,
    // MatSlideToggleModule,
    // MatRadioModule,
    // MatSliderModule,
    // MatNativeDateModule,
    // MatMenuModule,
    // MatPaginatorModule,
    // MatProgressSpinnerModule,
    // MatTabsModule,
  ],
  declarations: [],
})
export class MaterialModule {}
